export const medium = [
  "███████████ MY DATA ███████████",
  "► CUSTOM (enter below)",
  "ink drawing",
  "██████ PROMPTER CLOUD DATA ██████",
  "▬▬▬▬▬ Art Movements",
  "abstract expressionist art style",
  "art deco style",
  "art nouveau style",
  "avant-garde art style",
  "baroque art style",
  "bauhaus art style",
  "color field art style",
  "conceptual art style",
  "constructivism art style",
  "cubism art style",
  "dada art style",
  "expressionism art style",
  "fauvism art style",
  "fresco art style",
  "futurism art style",
  "harlem renaissance art style",
  "impressionism art style",
  "installation art style",
  "land art style",
  "minimalism art style",
  "neo-impressionism art style",
  "op art style",
  "pop art style",
  "post-impressionism art style",
  "precisionism art style",
  "psychedelic art style",
  "street art style",
  "suprematism art style",
  "surrealism art style",
  "symbolism art style",
  "▬▬▬▬▬ Flat Output",
  "3D rendering",
  "blueprint",
  "collage",
  "comic book",
  "digital art",
  "icon",
  "IKEA guide",
  "instruction manual",
  "magazine",
  "map",
  "mosaic",
  "movie poster",
  "newspaper",
  "photograph",
  "photorealism",
  "pixel art",
  "schematic",
  "signage",
  "stained glass",
  "sticker",
  "tattoo",
  "vector art",
  "woodblock print",
  "▬▬▬▬▬ Flat Output: Drawing",
  "anatomical drawing",
  "anime",
  "ballpoint pen drawing",
  "cartoon",
  "chalk",
  "chalkboard drawing",
  "charcoal drawing",
  "child's drawing",
  "collage",
  "colored pencil drawing",
  "coloring book",
  "comics",
  "crosshatch drawing",
  "doodle",
  "graphic novel",
  "illuminated manuscript",
  "india ink",
  "ink drawing",
  "marker drawing",
  "pastel",
  "pencil drawing",
  "pointillism",
  "stencil",
  "stipple",
  "storybook illustration",
  "tarot card",
  "trading card",
  "ukiyo-e",
  "▬▬▬▬▬ Flat Output: Painting",
  "airbrush painting",
  "cave painting",
  "color field painting",
  "glass painting",
  "glitter painting",
  "graffiti painting",
  "hydro-dipping painting",
  "light painting",
  "mural painting",
  "painting",
  "puffy paint painting",
  "scroll painting",
  "splatter painting",
  "spray painting",
  "still-life painting",
  "street art painting",
  "watercolor painting",
  "wet paint painting",
  "▬▬▬▬▬ Dimensional Output",
  "architecture",
  "balloon modeling",
  "bone china",
  "claymation",
  "cross-stitch",
  "diorama",
  "enamel pin",
  "etching",
  "ice sculpture",
  "origami",
  "paper model",
  "pottery",
  "relief carving",
  "resin",
  "rock art",
  "sculpture",
  "stained glass",
  "stone tablet",
  "string art",
  "textile",
  "wood carving",
  "yarn knitting",
  "▬▬▬▬▬ Photography",
  "photograph",
  "35mm film photograph",
  "agfacolor photograph",
  "ambrotype photograph",
  "calotype photograph",
  "collodion glass plate photograph",
  "cyanotype photograph",
  "daguerreotype photograph",
  "depth map photograph",
  "disposable camera photograph",
  "expired film photograph",
  "expired polaroid",
  "film negative photograph",
  "glamor photography",
  "hyperspectral imaging",
  "infrared photography",
  "instax photograph",
  "knolling photograph",
  "kodachrome photograph",
  "lomography photograph",
  "night vision photograph",
  "paparazzi photograph",
  "photogram photograph",
  "pinhole photograph",
  "polaroid photograph",
  "portrait photograph",
  "product photograph",
  "sepia photograph",
  "silhouette photograph",
  "tilt-shift lens photograph",
  "tintype photograph",
  "trail cam photograph",
  "ultraviolet photograph",
  "vintage film photograph",
  "▬▬▬▬▬ Displays",
  "1990s computer graphics",
  "4k",
  "ASCII",
  "atari graphics",
  "CRT display",
  "dot matrix display",
  "electroluminescent display",
  "holograph",
  "LCD display",
  "LED display",
  "pixel art",
  "quantum dot display",
  "VHS tape",
];

export const descriptor = [
  "► CUSTOM (enter below)",
  "███████████ MY DATA ███████████",
  "rorschach",
  "██████ PROMPTER CLOUD DATA ██████",
  "▬▬▬▬▬ Realism",
  "classical realism",
  "contemporary realism",
  "fantastic realism",
  "hyper realistic",
  "magic realism",
  "photorealistic",
  "realistic",
  "▬▬▬▬▬ Post-Realism",
  "abstract",
  "acidwave",
  "aura",
  "brutalism",
  "chakra",
  "cubism",
  "cyberpunk",
  "cyborgism",
  "dark fantasy",
  "dreamlike",
  "forestpunk",
  "fractalpunk",
  "futurism",
  "futuristic",
  "glo-fi",
  "nanopunk",
  "psychedelic",
  "psychedelica",
  "rainbowcore",
  "sci-fi",
  "shpongle",
  "sparklecore",
  "steampunk",
  "surreal",
  "synthwave",
  "vaporwave",
  "▬▬▬▬▬ Details: Simple, Basic",
  "depth of field",
  "flat",
  "flat shading",
  "minimalist",
  "simple",
  "▬▬▬▬▬ Details: Complex",
  "asymmetrical",
  "bling",
  "camouflage",
  "chaotic",
  "chart",
  "complex",
  "deep dream",
  "detailed",
  "diagram",
  "dreamcore",
  "fractal",
  "glassmorphism",
  "gliophorus-psittacinus",
  "graph",
  "grid",
  "high definition",
  "hyper realistic",
  "hyperbolic",
  "insanely detailed",
  "intricate",
  "kaleidoscope",
  "knotted",
  "luxury",
  "mandala",
  "mandelbrot",
  "mandelbulb",
  "maximum detail",
  "micro details",
  "molecular",
  "newton fractal",
  "ornate",
  "pattern",
  "rorschach",
  "sacred geometry",
  "seamless",
  "spirograph",
  "symmetrical",
  "trending on ArtStation",
  "Flickr",
  "DeviantArt",
  "▬▬▬▬▬ Rendering: Styles",
  "3D Render",
  "atari",
  "blender render",
  "cinema 4D",
  "cryengine",
  "houdini-render",
  "icon",
  "low poly",
  "microsoft paint",
  "nintendo",
  "octane",
  "openGL",
  "photoshop",
  "raylectron",
  "sketchup",
  "unreal engine",
  "vector graphic",
  "zbrush",
  "▬▬▬▬▬ Rendering: Reflections",
  "ray tracing reflections",
  "lumen reflections",
  "screen space reflections",
  "diffraction grating",
  "▬▬▬▬▬ Rendering: Properties",
  "transparent",
  "textured",
  "rough",
  "matte",
  "▬▬▬▬▬ Time",
  "1930s style",
  "1950s style",
  "1960s style",
  "1970s style",
  "1980s style",
  "1990s style",
  "Stone Age",
  "Bronze Age",
  "Iron Age",
  "Ancient Greece",
  "Ancient Rome",
  "Persian Empire",
  "Byzantine Empire",
  "Renaissance Humanism",
  "Protestant Reformation",
  "European Renaissance",
  "Enlightenment",
  "Industrial Revolution",
  "Age of Imperialism",
  "Victorian Era",
  "World War I",
  "Great Depression",
  "World War II",
  "antique",
  "medieval",
  "modern",
  "retro",
  "victorian",
  "vintage",
  "▬▬▬▬▬ Emotions Plus",
  "angelic",
  "angry",
  "annoyed",
  "anxious",
  "aversion",
  "bitter",
  "creepy",
  "demonic",
  "depressing",
  "​dislike",
  "dreamy",
  "dystopian",
  "ecstasy",
  "elegant",
  "elite",
  "evil",
  "excitement",
  "fashion",
  "frustrated",
  "gloomy",
  "grateful dead",
  "happy",
  "hopeless",
  "horrified",
  "horror",
  "infuriated",
  "insulted",
  "lonely",
  "luxury",
  "mad",
  "mellow",
  "miserable",
  "moody",
  "nauseated",
  "nervous",
  "offended",
  "ominous",
  "panicked",
  "revulsion",
  "sad",
  "satanic",
  "scared",
  "sleepy",
  "stressed",
  "tired",
  "vengeful",
  "whimsical",
  "worried",
  "▬▬▬▬▬ Seasons",
  "spring",
  "summer",
  "autumn",
  "winter",
  "▬▬▬▬▬ Holidays",
  "Bodhi Day",
  "Chinese New Year",
  "Christmas",
  "Cinco De Mayo",
  "Diwali",
  "Easter",
  "Eid al-Fitr",
  "Halloween",
  "Hanukkah",
  "Independence Day",
  "New Year",
  "Ramadan",
  "St. Patrick’s Day",
  "Thanksgiving",
  "Valentine’s Day",
  "▬▬▬▬▬ Elements",
  "ice",
  "fire",
  "liquid",
  "fog",
  "wind",
  "storm",
  "flood",
  "rain",
  "organic",
  "plasma",
  "▬▬▬▬▬ Shapes",
  "circle shape",
  "semi-circle shape",
  "oval shape",
  "square shape",
  "triangle shape",
  "rectangle shape",
  "polygonal shape",
  "cube shape",
  "sphere shape",
  "cone shape",
  "parallelogram shape",
  "rhombus shape",
  "trapezoid shape",
  "kite shape",
  "pentagon shape",
  "hexagon shape",
  "rubik cube shape",
  "organic shape",
  "▬▬▬▬▬ Backgrounds",
  "white background",
  "black background",
  "flat background",
  "textured background",
  "hazy background",
  "▬▬▬▬▬ Bodies",
  "attractive",
  "baby",
  "beautiful",
  "child",
  "cute",
  "fat",
  "female",
  "full body pose",
  "handsome",
  "male",
  "messy",
  "old",
  "short",
  "skinny",
  "tall",
  "ugly",
  "young",
];

export const camera = [
  "► CUSTOM (enter below)",
  "███████████ MY DATA ███████████",
  "fisheye lens",
  "██████ PROMPTER CLOUD DATA ██████",
  "▬▬▬▬▬ Small to Large",
  "super-resolution microscopy",
  "microscopy",
  "macro lens",
  "pinhole lens",
  "first person view",
  "wide angle lens",
  "ultra-wide angle lens",
  "fisheye lens",
  "telephoto lens",
  "panorama",
  "360 panorama",
  "tilt-shift lens",
  "telescope view",
  "drone view",
  "aerial",
  "from above",
  "satellite imagery",
  "▬▬▬▬▬ Other Terms",
  "blurry",
  "bokeh",
  "ICM",
  "long exposure",
  "motion blur",
  "soft focus",
  "▬▬▬▬▬ Lens Lengths",
  "8mm lens",
  "35mm lens",
  "50mm lens",
  "80mm lens",
  "200mm lens",
  "500mm lens",
];

export const lighting = [
  "► CUSTOM (enter below)",
  "███████████ MY DATA ███████████",
  "lantern",
  "██████ PROMPTER CLOUD DATA ██████",
  "▬▬▬▬▬ Styles",
  "bright lighting",
  "campfire lighting",
  "candlelight",
  "cinematic lighting",
  "colorful lighting",
  "contre-jour lighting",
  "dark lighting",
  "dramatic lighting",
  "early morning lighting",
  "film noir lighting",
  "golden hour sunlight",
  "hard lighting",
  "moody lighting",
  "night lighting",
  "realistic lighting",
  "soft lighting",
  "studio lighting",
  "sunset lighting",
  "volumetric lighting",
  "▬▬▬▬▬ Types",
  "backlight",
  "bioluminescence",
  "black light bulb",
  "candle light",
  "christmas lights",
  "crepuscular rays",
  "daylight",
  "edison bulb",
  "fire light",
  "floodlight",
  "fluorescent bulb",
  "glow in the dark light",
  "glow stick",
  "glowing light",
  "halfrear lighting",
  "infrared light",
  "lantern light",
  "laser light",
  "LED lights",
  "lens flare",
  "light rays",
  "natural lighting",
  "neon bulb",
  "nixie tube bulb",
  "plasma globe",
  "silhouette lighting",
  "spotlight",
  "sunlight",
  "vacuum tube bulb",
  "x-ray",
];

export const color = [
  "► CUSTOM (enter below)",
  "███████████ MY DATA ███████████",
  "rainbow color",
  "██████ PROMPTER CLOUD DATA ██████",
  "▬▬▬▬▬ Grayscale",
  "white",
  "black",
  "light gray",
  "dark gray",
  "▬▬▬▬▬ Colors",
  "maroon",
  "red",
  "orange",
  "yellow",
  "lime",
  "green",
  "cyan",
  "teal",
  "blue",
  "indigo",
  "purple",
  "violet",
  "brown",
  "▬▬▬▬▬ Colors (dark)",
  "dark-maroon",
  "dark-red",
  "dark-orange",
  "dark-yellow",
  "dark-lime",
  "dark-green",
  "dark-cyan",
  "dark-teal",
  "dark-blue",
  "dark-indigo",
  "dark-purple",
  "dark-violet",
  "dark-brown",
  "▬▬▬▬▬ Colors (light)",
  "light-maroon",
  "light-red",
  "light-orange",
  "light-yellow",
  "light-lime",
  "light-green",
  "light-cyan",
  "light-teal",
  "light-blue",
  "light-indigo",
  "light-purple",
  "light-violet",
  "light-brown",
  "▬▬▬▬▬ Styles",
  "black and white",
  "complementary color",
  "cool color",
  "dark color",
  "dichromatism color",
  "faded color",
  "high contrast",
  "inverted color",
  "light color",
  "low contrast",
  "monochromatic color",
  "muted color",
  "neon color",
  "pantone color",
  "pastel color",
  "rainbow color",
  "saturated color",
  "sepia color",
  "spectral solar",
  "vibrant color",
  "vivid color",
  "warm color",
  "▬▬▬▬▬ Displays",
  "RGB",
  "CMYK",
  "1-bit grayscale",
  "4-bit grayscale",
  "3-bit color",
  "6-bit color",
  "technicolor",
  "▬▬▬▬▬ Seasonal Colors",
  "spring colors",
  "summer colors",
  "autumn colors",
  "winter colors",
  "▬▬▬▬▬ Color Mix Styles",
  "camouflage color",
  "confetti color",
  "diffraction pattern color",
  "disco color",
  "funky color",
  "gradient color",
  "halftone color",
  "polka dot color",
  "pop-art color",
  "purity color",
  "spectrum color",
  "synesthesia color",
  "tie-dye color",
  "▬▬▬▬▬ Photography",
  "35mm film color",
  "agfacolor color",
  "ambrotype color",
  "bokeh color",
  "calotype color",
  "chromatic aberration color",
  "collodion glass plate color",
  "cyanotype color",
  "daguerreotype color",
  "depth map color",
  "expired film color",
  "expired polaroid",
  "film negative color",
  "fujifilm digital",
  "hyperspectral imaging color",
  "instax color",
  "kodachrome color",
  "kodak gold 200 film color",
  "lomography color",
  "night vision color",
  "photogram color",
  "polaroid color",
  "sepia photograph color",
  "tintype color",
  "tri-x 400 tx color",
  "ultraviolet color",
  "vignette color",
  "vintage film color",
];

export const artists = [
  "► CUSTOM (enter below)",
  "███████████ MY DATA ███████████",
  "Salvador Dalí",
  "██████ PROMPTER CLOUD DATA ██████",
  "▬▬▬▬▬ Art Movements",
  "▬▬▬▬▬ Abstract Expressionism (1940-1950, abstract, dripping, spilling)",
  "Ad Reinhardt",
  "Barnett Newman",
  "Clyfford Still",
  "Cy Twombly",
  "Franz Kline",
  "Helen Frankenthaler",
  "Jackson Pollock",
  "Lee Krasner",
  "Mark Rothko",
  "Robert Motherwell",
  "Willem de Kooning",
  "▬▬▬▬▬ Art Deco (1920-1940, Europe and USA, craftsmanship, design, color, text)",
  "Eugene Grasset",
  "Hector Guimard",
  "Jean Gabriel Domergue",
  "Paul Poiret",
  "Raoul Dufy",
  "Sonia Delaunay",
  "Tamara de Lempicka",
  "▬▬▬▬▬ Art Nouveau (1880-1910, asymmetrical and organic, bold design)",
  "Alphonse Mucha",
  "Antoni Gaudí",
  "Aubrey Beardsley",
  "Eugene Grasset",
  "Gustav Klimt",
  "Henri de Toulouse-Lautrec",
  "Jan Toorop",
  "Louis Comfort Tiffany",
  "Victor Horta",
  "▬▬▬▬▬ Avant-Garde (1910-1980, breaking barriers, new ideas, new mediums)",
  "Kazimir Malevich",
  "Paul Klee",
  "Pablo Picasso",
  "Piero Manzoni",
  "Robert Smithson",
  "Joseph Beuys",
  "Jean-Michel Basquiat",
  "Marina Abramovic",
  "▬▬▬▬▬ Baroque (1590-1740, dramatic, motion, action)",
  "Annibale Carracci",
  "Domenikos Theotokopoulos",
  "Francesco Borromini",
  "Gian Lorenzo Bernini",
  "Johannes Vermeer van Delft",
  "Michelangelo Merisi da Caravaggio",
  "Peter Paul Rubens",
  "Rembrandt van Rijn",
  "▬▬▬▬▬ Bauhaus (1919-1933, German, art and architecture)",
  "Walter Gropius",
  "Ludwig Mies van der Rohe",
  "Paul Klee",
  "Wassily Kandinsky",
  "László Moholy-Nagy",
  "▬▬▬▬▬ Color Field Painting (1950-1960, pure abstraction, color, shape)",
  "Alma Thomas",
  "Barnett Newman",
  "Clyfford Still",
  "Helen Frankenthaler",
  "John Hoyland",
  "Kenneth Noland",
  "Mark Rothko",
  "Morris Louis",
  "Sam Gilliam",
  "▬▬▬▬▬ Conceptual (1960-1970, ideas and concepts over visual)",
  "Hans Haacke",
  "John Baldessari",
  "Joseph Kosuth",
  "Marina Abramović",
  "Mel Bochner",
  "On Kawara",
  "Sol LeWitt",
  "▬▬▬▬▬ Constructivism (1915-1940, Soviet Union, Germany, art for social purposes)",
  "Alexander Rodchenko",
  "El Lissitzky",
  "Liubov Popova",
  "▬▬▬▬▬ Cubism (1907, two-dimensional form of the canvas)",
  "Pablo Picasso",
  "Georges Braque",
  "Fernand Léger",
  "Alexander Archipenko",
  "▬▬▬▬▬ Dada / Dadaism (1916-1924, WWI, remove logic)",
  "Francois Picabia",
  "Hannah Höch",
  "Hans Arp",
  "Man Ray",
  "Marcel Duchamp",
  "Sophie Taeuber-Arp",
  "▬▬▬▬▬ Expressionism (1905-1920, Germany and Austria, emotional experience)",
  "Vincent van Gogh",
  "Henri Matisse",
  "Edvard Munch",
  "Egon Schiele",
  "Oskar Kokoschka",
  "Wassily Kandinsky",
  "Franz Marc",
  "Ernst Ludwig Kirchner",
  "▬▬▬▬▬ Fauvism (vibrant color, brushstrokes)",
  "André Derain",
  "Henri Matisse",
  "Maurice de Vlaminck",
  "▬▬▬▬▬ Futurism (1908-1944, Italy, speed and energy of the modern world)",
  "Filippo Tommaso Marinetti",
  "Giacomo Balla",
  "Gino Severini",
  "Luigi Russolo",
  "Umberto Boccioni",
  "▬▬▬▬▬ Harlem Renaissance (1919-1930, Harlem NY, African American culture, identity, pride)",
  "Aaron Douglas",
  "Archibald John Motley",
  "Beauford Delaney",
  "Jacob Lawrence",
  "James van der Zee",
  "▬▬▬▬▬ Impressionism (1867-1886, Italy, record impressions, thin brush strokes, dreamy)",
  "Alfred Sisley",
  "Camille Pissarro",
  "Claude Monet",
  "Edgar Degas",
  "Paul Cézanne",
  "Pierre Auguste Renoir",
  "▬▬▬▬▬ Installation Art (1950, physical, large, mixed media)",
  "Doris Salcedo",
  "Gordon Matta-Clark",
  "Jason Rhoades",
  "Judy Chicago",
  "Kara Walker",
  "Kurt Schwitters",
  "Marcel Broodthaers",
  "Thomas Hirschhorn",
  "Yayoi Kusama",
  "▬▬▬▬▬ Land Art (1960, nature, shape and form and physical space)",
  "Ana Mendieta",
  "Andy Goldsworthy",
  "Christo and Jeanne-Claude",
  "Michael Heizer",
  "Richard Long",
  "Robert Smithson",
  "▬▬▬▬▬ Minimalism (1960-1970, simple, abstract, geometric shapes, no representation)",
  "Agnes Martin",
  "Carl Andre",
  "Dan Flavin",
  "Donald Judd",
  "Frank Stella",
  "Larry Bell",
  "Robert Irwin",
  "Sol Lewitt",
  "▬▬▬▬▬ Neo-Impressionism (1880, France, systematic painting, pointillism)",
  "Georges Seurat",
  "Paul Signac",
  "▬▬▬▬▬ Neon Art (1960, advertising as medium, neon lights)",
  "Alex Da Corte",
  "Dan Flavin",
  "Glenn Ligon",
  "Joseph Kosuth",
  "Keith Sonnier",
  "Tim Noble and Sue Webster",
  "Tracey Emin",
  "▬▬▬▬▬ Op Art (1950-1960, visual effects, optical illusion, perception)",
  "Bridget Riley",
  "François Morellet",
  "Jesús Rafael Soto",
  "Julio Le Parc",
  "Victor Vasarely",
  "▬▬▬▬▬ Performance Art (1960, acting for an audience or camera, events, happenings)",
  "Ana Mendieta",
  "Guerilla Girls",
  "Marina Abramovich",
  "Nick Cave",
  "Tehching Hsieh",
  "Yoko Ono",
  "▬▬▬▬▬ Pop Art (1950-1960, popular culture, commercial culture)",
  "Andy Warhol",
  "Claes Oldenburg",
  "David Hockney",
  "Richard Hamilton",
  "Robert Rauschenberg",
  "Roy Lichtenstein",
  "▬▬▬▬▬ Post-Impressionism (1886-1905, reaction against impressionism, bold colors, symbolic imagery)",
  "Camille Pissarro",
  "Georges Seurat",
  "Henri Rousseau",
  "Paul Gauguin",
  "Toulouse Lautrec",
  "Vincent van Gogh",
  "▬▬▬▬▬ Precisionism (1920-1930, cubism and futurism, sharp focus, industrialization)",
  "Charles Demuth",
  "Charles Sheeler",
  "Edward Hopper",
  "George Ault",
  "Georgia O’Keeffe",
  "Joseph Stella",
  "▬▬▬▬▬ Street Art (1960s, graffiti, illegal art, murals, urban art)",
  "Banksy",
  "Jean Michel Basquiat",
  "Keith Haring",
  "Lady Pink",
  "Shepard Fairey",
  "▬▬▬▬▬ Surrealism (1920-1960, Paris, WWII, rational and irrational, dreams, poetry)",
  "André Breton",
  "André Masson",
  "Diego Rivera",
  "Frida Kahlo",
  "Jean Arp",
  "Joan Miró",
  "Man Ray",
  "Max Ernst",
  "Meret Oppenheim",
  "Rene Magritte",
  "Salvador Dalí",
  "Shane McGeehan",
  "Wifredo Lam",
  "Yves Tanguy",
  "▬▬▬▬▬ Suprematism (1910-1920, Russia, simple geometric forms, color, very minimal)",
  "El Lissitzky",
  "Kazimir Malevich",
  "Mikhail Menkov",
  "▬▬▬▬▬ Symbolism (1880-1920, objects as symbols, emotions, weariness of modernity)",
  "Arnold Böcklin",
  "Edvard Munch",
  "Fernand Khnopff",
  "Gustav Klimt",
  "Gustave Moreau",
  "Jan Toorop",
  "Odilon Redon",
  "Paul Gauguin",
  "▬▬▬▬▬ Zero Group (1950-1960, Germany, materiality, color, vibration, light, abstract)",
  "Günther Uecker",
  "Heinz Mack",
  "Jean Tinguely",
  "Lucio Fontana",
  "Otto Piene",
  "Piero Manzoni",
  "Yayoi Kusama",
  "Yves Klein",
  "▬▬▬▬▬ Photography (oh you know, cameras and stuff since 1826, thanks Niépce)",
  "Aaron Siskind",
  "Alexander Rodchenko",
  "Alfred Stieglitz",
  "Alvin Langdon Coburn",
  "Andre Kertesz",
  "Andres Serrano",
  "Ansel Adams",
  "Arnold Newman",
  "August Sander",
  "Barbara Kruger",
  "Berenice Abbott",
  "Bernd and Hilla Becher",
  "Bill Brandt",
  "Brassai",
  "Carleton E Watkins",
  "Carrie Mae Weems",
  "Cindy Sherman",
  "Clarence John Laughlin",
  "David Levinthal",
  "Dawoud Bey",
  "Diane Arbus",
  "Dorothea Lange",
  "Duane Michals",
  "Eadweard Muybridge",
  "Edward Burtynsky",
  "Edward Steichen",
  "Edward Weston",
  "Emmet Gowin",
  "Eugene Atget",
  "Eugène Atget",
  "Francesca Woodman",
  "Garry Winogrand",
  "Garry Winogrand",
  "Gertrude Käsebier",
  "Gordon Parks",
  "Gustave Le Gray",
  "Hans Bellmer",
  "Harold Edgerton",
  "Harry Callahan",
  "Helen Levitt",
  "Henry Peach Robinson",
  "Hiroshi Sugimoto",
  "Imogen Cunningham",
  "Jacob Riis",
  "Jacques Henri Lartigue",
  "Jerry Uelsmann",
  "Joel Meyerowitz",
  "Joel Peter Witkin",
  "John Gutmann",
  "Josef Koudelka",
  "Julia Margaret Cameron",
  "Kahn and Selesnick",
  "Karl Blossfeldt",
  "László Moholy-Nagy",
  "Lee Friedlander",
  "Lewis Carroll",
  "Lewis Hine",
  "Lisette Model",
  "Lothar Wolleh",
  "Louis Daguerre",
  "Margaret Bourke White",
  "Matthew Brandt",
  "Minor White",
  "Nadar",
  "Paul Outerbridge",
  "Paul Strand",
  "Ralph Eugene Meatyard",
  "Richard Avedon",
  "Robert Adams",
  "Robert and Shana ParkeHarrison",
  "Robert Frank",
  "Roger Fenton",
  "Roy DeCarava",
  "Sandy Skoglund",
  "Sebastiao Salgado",
  "Shane McGeehan",
  "Sophie Calle",
  "Stephen Shore",
  "Timothy O'Sullivan",
  "Tina Modotti",
  "W Eugene Smith",
  "Walker Evans",
  "Weegee",
  "William Eggleston",
  "William Henry Fox Talbot",
  "William Klein",
  "Yousuf Karsh",
  "▬▬▬▬▬ AI Trained Artists (list from Sincarnate)",
  "Aaron Horkey",
  "Abigail Larson",
  "Adolph Menzel",
  "Affandi",
  "Agnes Lawrence Pelton",
  "Akihiko Yoshida",
  "Akira Toriyama",
  "Al Williamson",
  "Alan Lee",
  "Albert Bierstadt",
  "Alberto Giacometti",
  "Alberto Vargas",
  "Albrecht Dürer",
  "Aleksi Briclot",
  "Alena Aenami",
  "Alex Grey",
  "Alexander Jansson",
  "Alexander Milne Calder",
  "Alexandre Cabanel",
  "Alexei Savrasov",
  "Alexej von Jawlensky",
  "Alfred Kubin",
  "Alice Neel",
  "Alphonso Mucha",
  "Alyssa Monks",
  "Amanda Sage",
  "Amedeo Modigliani",
  "André Masson",
  "Andreas Rocha",
  "Andrew Wyeth",
  "Andy Warhol",
  "Angus McKie",
  "Anna Dittmann",
  "Anne Geddes",
  "Anne McCaffrey",
  "Anne Stokes",
  "Annibale Carracci",
  "Ansel Adams",
  "Anthony van Dyck",
  "Anton Otto Fischer",
  "Anton Pieck",
  "Apollonia Saintclair",
  "Arkhip Kuindzhi",
  "Arnold Böcklin",
  "Arshile Gorky",
  "Art Spiegelman",
  "Artemisia Gentileschi",
  "Artgerm",
  "Arthur Dove",
  "Arthur Rackham",
  "Asaf Hanuka",
  "Asher Brown Durand",
  "Ashley Wood",
  "Atey Ghailan",
  "Aubrey Beardsley",
  "Audrey Kawasaki",
  "August Macke",
  "Augustus Edwin Mulready",
  "Austin Briggs",
  "Ayami Kojima",
  "Barclay Shaw",
  "Bastien Lecouffe-Deharme",
  "Bauhaus",
  "Beatrix Potter",
  "Beauford Delaney",
  "Ben Shahn",
  "Ben Templesmith",
  "Benoit B. Mandelbrot",
  "Bernard Buffet",
  "Bernie Wrightson",
  "Bjarke Ingels",
  "Bob Byerley",
  "Bob Eggleton",
  "Bob Ross",
  "Bonnard Pierre",
  "Boris Vallejo",
  "Brian Bolland",
  "Brian Despain",
  "Brian Froud",
  "Brian Kesinger",
  "Bridget Bate Tichenor",
  "Bridget Riley",
  "Brothers Hildebrandt",
  "Bruce Pennington",
  "Camille Corot",
  "Camille Pissarro",
  "Camille-Pierre Pambu Bodo",
  "Canaletto",
  "Candido Portinari",
  "Caravaggio",
  "Carl Barks",
  "Carl Holsoe",
  "Carl Larsson",
  "Carne Griffiths",
  "Caspar David Friedrich",
  "cgsociety",
  "Chaïm Soutine",
  "Charles Blackman",
  "Charles E. Burchfield",
  "Charles Eames",
  "Charles Schulz",
  "Charlie Bowater",
  "Chesley Bonestell",
  "Chiharu Shiota",
  "Childe Hassam",
  "Chris Foss",
  "Chris Mars",
  "Chris Moore",
  "Cicely Mary Barker",
  "Cindy Sherman",
  "Claude Cahun",
  "Claude Lorrain",
  "Claude Monet",
  "Clyde Caldwell",
  "Coby Whitmore",
  "Codex Seraphinianus",
  "Coles Phillips",
  "Conrad Roset",
  "Cory Loftis",
  "Craig Davison",
  "Craig Mullins",
  "Craola",
  "Cuno Amiet",
  "Dan Flavin",
  "Dan Mumford",
  "Daniel Gerhartz",
  "Daniel Merriam",
  "Daniel Ridgway Knight",
  "Dave Dorman",
  "Dave Gibbons",
  "Dave McKean",
  "David B. Mattingly",
  "David Burliuk",
  "David Hockney",
  "Dean Ellis",
  "Diane Arbus",
  "Diego Rivera",
  "Diego Velázquez",
  "Don Bluth",
  "Don Maitz",
  "Donato Giancola",
  "Dora Maar",
  "Dorothea Tanning",
  "Dorothy Lathrop",
  "Doug Chiang",
  "Dr. Seuss",
  "Dustin Nguyen",
  "Earl Norem",
  "Ed Binkley",
  "Ed Emshwiller",
  "Eddie Campbell",
  "Eddie Mendoza",
  "Edgar Degas",
  "Edmund Dulac",
  "Edmund Leighton",
  "Édouard Manet",
  "Edvard Munch",
  "Edward Burne-Jones",
  "Edward Gorey",
  "Edward Hopper",
  "Edward Lear",
  "Edward Robert Hughes",
  "Edward Weston",
  "Egon Schiele",
  "El Greco",
  "Elaine de Kooning",
  "Ellen Jewett",
  "Elliott Erwitt",
  "Elsa Beskow",
  "Emil Melmoth",
  "Emil Nolde",
  "Émile Bernard",
  "Enki Bilal",
  "Eric Lacombe",
  "Erich Heckel",
  "Ernst Fuchs",
  "Ernst Haeckel",
  "Ernst Ludwig Kirchner",
  "Esao Andrews",
  "Eugene Delacroix",
  "Evelyn De Morgan",
  "Eyvind Earle",
  "Farel Dalrymple",
  "Fenghua Zhong",
  "Fernando Botero",
  "Filippino Lippi",
  "Francis Bacon",
  "Francis Picabia",
  "Francisco Goya",
  "Frank Auerbach",
  "Frank Frazetta",
  "Frank Miller",
  "Frank Schoonover",
  "Frank Zappa",
  "Franklin Booth",
  "Franz Marc",
  "Franz Sedlacek",
  "Franz Xaver Winterhalter",
  "Fred Tomaselli",
  "Frederick Lord Leighton",
  "Frida Kahlo",
  "Friedensreich Regentag Dunkelbunt Hundertwasser",
  "Frits Van den Berghe",
  "Gabriele Münter",
  "Garry Trudeau",
  "Gary Larson",
  "Gaston Bussière",
  "Gediminas Pranckevicius",
  "Geof Darrow",
  "George Frederic Watts",
  "George Grosz",
  "George Inness",
  "George Luks",
  "Georges Rouault",
  "Georges Seurat",
  "Georgia O’Keeffe",
  "Gerald Brom",
  "Gerhard Munthe",
  "Gerhard Richter",
  "Giorgio de Chirico",
  "Giovanni Battista Gaulli",
  "Giovanni Battista Piranesi",
  "Giuseppe Arcimboldo",
  "Glenn Fabry",
  "Go Nagai",
  "Gottfried Helnwein",
  "Greg Hildebrandt",
  "Greg Rutkowski",
  "Gregory Crewdson",
  "Guido Borelli da Caluso",
  "Gustav Klimt",
  "Gustav Vigeland",
  "Gustave Courbet",
  "Gustave Doré",
  "Gustave Moreau",
  "Gustave Van de Woestijne",
  "H. R. Giger",
  "H.P. Lovecraft",
  "Hal Foster",
  "Hannah Hoch",
  "Hans Baldung",
  "Hans Bellmer",
  "Harold Elliott",
  "Harriet Backer",
  "Harry Clarke",
  "Heinrich Kley",
  "Heinrich Lefler",
  "Helmut Newton",
  "Hendrik Kerstens",
  "Henri de Toulouse-Lautrec",
  "Henri Harpignies",
  "Henri Matisse",
  "Henri Rousseau",
  "Henri-Edmond Cross",
  "Henry Fuseli",
  "Henry Ossawa Tanner",
  "Hieronymus Bosch",
  "Hilma af Klint",
  "Hirohiko Araki",
  "Hiromu Arakawa",
  "Hiroshi Nagai",
  "Hiroshi Yoshida",
  "Hong SoonSang",
  "Honoré Daumier",
  "Hope Gangloff",
  "Howard Finster",
  "Howard Hodgkin",
  "Hubert Robert",
  "Hugh Ferriss",
  "Hugh Kretschmer",
  "Hundertwasser",
  "Ian McQue",
  "Ian Miller",
  "Igor Morski",
  "Ilya Kuvshinov",
  "Ilya Repin",
  "Irma Stern",
  "Isaac Levitan",
  "Ismail Inceoglu",
  "Ivan Aivazovsky",
  "Ivan Albright",
  "Ivan Bilibin",
  "Ivan Shishkin",
  "J. J. Grandville",
  "J.C. Leyendecker",
  "J.M.W. Turner",
  "Jacek Yerka",
  "Jack Butler Yeats",
  "Jack Davis",
  "Jack Gaughan",
  "Jack Kirby",
  "Jackson Pollock",
  "Jacob van Ruisdael",
  "Jakub Rozalski",
  "James Abbott McNeill Whistler",
  "James C. Christensen",
  "James Ensor",
  "James Gurney",
  "James Jean",
  "James Turrell",
  "Jamie Hewlett",
  "Jan van Goyen",
  "Jaroslaw Jasnikowski",
  "Jasmine Becket-Griffith",
  "Jason Edmiston",
  "Jason Limon",
  "Jean Arp",
  "Jean Delville",
  "Jean Giraud",
  "Jean Metzinger",
  "Jean-Antoine Watteau",
  "Jean-Baptiste Monge",
  "Jean-Honoré Fragonard",
  "Jean-Michel Basquiat",
  "Jean-Pierre Vasarely",
  "Jeff Easley",
  "Jeff Koons",
  "Jeff Lemire",
  "Jeffrey Catherine Jones",
  "Jeffrey Smith",
  "Jeffrey T. Larson",
  "Jeremy Geddes",
  "Jeremy Lipking",
  "Jeremy Mann",
  "Jesper Ejsing",
  "Jim Burns",
  "Jim Fitzpatrick",
  "Jim Lee",
  "Jim Steranko",
  "Joan Miro",
  "Joaquín Sorolla",
  "Johan Christian Dahl",
  "Johannes Vermeer",
  "Johfra Bosschart",
  "John Atkinson Grimshaw",
  "John Bauer",
  "John Berkey",
  "John Blanche",
  "John Constable",
  "John Duncan",
  "John Frederick Kensett",
  "John Harris",
  "John Howe",
  "John Hoyland",
  "John James Audubon",
  "John Kenn Mortensen",
  "John Martin",
  "John Perceval",
  "John Philip Falter",
  "John Romita Jr",
  "John Singer Sargent",
  "John Stephens",
  "John William Waterhouse",
  "Jon Klassen",
  "Josan Gonzalez",
  "Joseph Cornell",
  "Joseph Ducreux",
  "Joseph Stella",
  "Josephine Wall",
  "Jules Bastien-Lepage",
  "Junji Ito",
  "Justin Gerard",
  "Kaethe Butcher",
  "Kaja Foglio",
  "Karl Blossfeldt",
  "Karl Schmidt-Rottluff",
  "Karol Bak",
  "Kate Greenaway",
  "Käthe Kollwitz",
  "Kati Horna",
  "Katsushika Hokusai",
  "Kay Nielsen",
  "Kay Sage",
  "Kazimir Malevich",
  "Kehinde Wiley",
  "Keith Haring",
  "Kelly Freas",
  "Kelly McKernan",
  "Ken Sugimori",
  "Kengo Kuma",
  "Kent Monkman",
  "Kentaro Miura",
  "Kilian Eng",
  "Kim Jung Gi",
  "Krenz Cushart",
  "Kuang Hong",
  "Larry Elmore",
  "Laurel Burch",
  "Laurie Greasley",
  "Laurie Lipton",
  "Lawren Harris",
  "Le caravaggesque",
  "Lee Madgwick",
  "Leiji Matsumoto",
  "Leon Kossoff",
  "Leonardo da Vinci",
  "Leonid Afremov",
  "Lisa Frank",
  "Louis Comfort Tiffany",
  "Louis Wain",
  "Lovis Corinth",
  "Luc Schuiten",
  "Lucian Freud",
  "Luis Royo",
  "Lyonel Feininger",
  "Lyubov Popova",
  "M.C. Escher",
  "M.W. Kaluta",
  "Mab Graves",
  "Makoto Shinkai",
  "Malcolm Liepke",
  "Man Ray",
  "Marc Chagall",
  "Marc Simonetti",
  "Marcell Chagall",
  "Marco Mazzoni",
  "Margaret Macdonald Mackintosh",
  "Maria Sibylla Merian",
  "Marianne North",
  "Marianne von Werefkin",
  "Marius Borgeaud",
  "Mark Brooks",
  "Mark Rothko",
  "Mark Ryden",
  "Marsden Hartley",
  "Martin Johnson Heade",
  "Martiros Saryan",
  "Mary Blair",
  "Masaaki Sasamoto",
  "Masamune Shirow",
  "Mat Collishaw",
  "Mati Klarwein",
  "Matt Groening",
  "Matthias Grünewald",
  "Matti Suuronen",
  "Maurice Sendak",
  "Max Beckmann",
  "Max Ernst",
  "Max Pechstein",
  "Max Weber",
  "Maxfield Parrish",
  "Méret Oppenheim",
  "Michael Deforge",
  "Michael Whelan",
  "Michelangelo",
  "Michal Lisowski",
  "Miho Hirano",
  "Mikalojus Konstantinas Ciurlionis",
  "Mike Mignola",
  "Mike Winkelmann",
  "Mikhail Vrubel",
  "Milton Avery",
  "Milton Glaser",
  "Moebius",
  "Naoto Hattori",
  "Natalia Goncharova",
  "Neil Welliver",
  "Nele Zirnite",
  "Nicholas Roerich",
  "Nick Knight",
  "Noah Bradley",
  "Nobuyoshi Araki",
  "Noriyoshi Ohrai",
  "Norman Rockwell",
  "Odd Nerdrum",
  "Odilon Redon",
  "Okuda San Miguel",
  "Oskar Kokoschka",
  "Otto Dix",
  "Otto Marseus van Schrieck",
  "Pablo Picasso",
  "Pascal Blanché",
  "Pascal Campion",
  "Patrick Heron",
  "Patrick Woodroffe",
  "Paul Cézanne",
  "Paul Delvaux",
  "Paul Gauguin",
  "Paul Gustav Fischer",
  "Paul Klee",
  "Paul Lehr",
  "Paul Rand",
  "Paula Modersohn-Becker",
  "Peter Bagge",
  "Peter Elson",
  "Peter Gric",
  "Peter Max",
  "Peter Mohrbacher",
  "Peter Paul Rubens",
  "Phil Foglio",
  "Philip Guston",
  "Philippe Druillet",
  "Pierre-Auguste Renoir",
  "Piet Mondrian",
  "Pieter Bruegel the Elder",
  "Pieter Claesz",
  "Quentin Blake",
  "Rafal Olbinski",
  "Ralph McQuarrie",
  "Randolph Caldecott",
  "Raphael",
  "Raphael Lacoste",
  "Raphaelite",
  "Ray Caesar",
  "Raymond Briggs",
  "Raymond Swanland",
  "Rebecca Guay",
  "Rembrandt van Rijn",
  "Remedios Varo",
  "Rene Magritte",
  "RHADS",
  "Richard Corben",
  "Richard Dadd",
  "Richard Doyle",
  "Richard Scarry",
  "Ridley Scott",
  "Rob Gonsalves",
  "Rob Liefeld",
  "Robert Bechtle",
  "Robert Crumb",
  "Robert McCall",
  "Robert Motherwell",
  "Robert Rauschenberg",
  "Robert Williams",
  "Roberto Ferri",
  "Roberto Matta",
  "Rockwell Kent",
  "Rodney Matthews",
  "Roger Dean",
  "Ron Walotsky",
  "Ross Tran",
  "Roy Lichtenstein",
  "Ruan Jia",
  "Rudolf Hausner",
  "Rufino Tamayo",
  "Russ Mills",
  "Ryan Hewett",
  "Ryohei Hase",
  "Sailor Moon",
  "Sally Mann",
  "Salvador Dalí",
  "Sam Bosma",
  "Sam Guay",
  "Sandro Botticelli",
  "Santiago Caruso",
  "Satoshi Kon",
  "Sergio Toppi",
  "Shaun Tan",
  "Shepard Fairey",
  "Shiki",
  "Shinji Aramaki",
  "Shotaro Ishinomori",
  "Sidney Nolan",
  "Sidney Prior Hall",
  "Simon Bisley",
  "Simon Stalenhag",
  "Sir James Guthrie",
  "Sonia Delaunay",
  "Stanley Donwood",
  "Stefan Gesell",
  "Stephanie Law",
  "Stephen Gammell",
  "Steve Argyle",
  "Steve Dillon",
  "Steve Ditko",
  "Storm Thorgerson",
  "Stuart Davis",
  "Studio Ghibli",
  "Syd Mead",
  "Taiyō Matsumoto",
  "Takashi Murakami",
  "Takato Yamamoto",
  "Takehiko Inoue",
  "Taro Okamoto",
  "Tatsuro Kiuchi",
  "Ted Nasmith",
  "Terry Oakes",
  "Tex Avery",
  "Theodore Robinson",
  "Thomas Cole",
  "Thomas Gainsborough",
  "Thomas Kinkade",
  "Tibor Nagy",
  "Tim Burton",
  "Tim Doyle",
  "Tim Hildebrandt",
  "Tim White",
  "Titian",
  "Tivadar Csontváry Kosztka",
  "Todd McFarlane",
  "Tom Bagshaw",
  "Tom Lovell",
  "Tom Thomson",
  "Tomer Hanuka",
  "Tomokazu Matsuyama",
  "Tony DiTerlizzi",
  "Tsutomu Nihei",
  "Tyler Edlin",
  "Ub Iwerks",
  "Victo Ngai",
  "Victor Adame Minguez",
  "Victor Brauner",
  "Victor Moscoso",
  "Victor Vasarely",
  "Viktor Vasnetsov",
  "Vilhelm Hammershoi",
  "Vincent Van Gogh",
  "Virgil Finlay",
  "Walt Disney",
  "Walter Crane",
  "Warwick Goble",
  "Wassily Kandinsky",
  "Wayne Barlowe",
  "Wendy Froud",
  "Wes Anderson",
  "Wifredo Lam",
  "Will Eisner",
  "Willem de Kooning",
  "Willem van Haecht",
  "William Blake",
  "William Gropper",
  "William Henry Hunt",
  "William Hogarth",
  "William Morris",
  "William S Burroughs",
  "William Stout",
  "William-Adolphe Bouguereau",
  "Winslow Homer",
  "Yaacov Agam",
  "Yanjun Cheng",
  "Yayoi Kusama",
  "Yoji Shinkawa",
  "Yoshitaka Amano",
  "Yuumei",
  "Yves Klein",
  "Yves Tanguy",
  "Zack Snyder",
  "Zaha Hadid",
  "Zdzislaw Beksinski",
];

export const film = [
  "► CUSTOM (enter below)",
  "███████████ MY DATA ███████████",
  "Stranger Things",
  "██████ PROMPTER CLOUD DATA ██████",
  "▬▬▬▬▬ Movies $ TV",
  "2001 A Space Odyssey",
  "Adaptation",
  "Amelie",
  "American Graffiti",
  "Apocalypse Now",
  "Arrival",
  "Being John Malkovich",
  "Birdman",
  "Blade Runner",
  "Brazil",
  "Citizen Kane",
  "City of God",
  "Dark Knight",
  "Dogville",
  "Drive",
  "Dune",
  "Enemy",
  "Enter the Void",
  "Eraserhead",
  "Eternal Sunshine Of The Spotless Mind",
  "Fargo",
  "Gravity",
  "Hook",
  "Interstellar",
  "It",
  "La La Land",
  "Labyrinth",
  "Life of Pi",
  "Mad Max Fury Road",
  "Metropolis",
  "Momento",
  "Neon Demon",
  "Oblivion",
  "Only God Forgives",
  "Paprika",
  "Pleasantville",
  "Psycho",
  "Pulp Fiction",
  "Spirited Away",
  "Star Wars",
  "Stranger Things",
  "Suspiria",
  "The Artist",
  "The Cell",
  "The Fall",
  "The Grand Budapest Hotel",
  "The Joker",
  "The Nightmare Before Christmas",
  "The Revenant",
  "The Shape of Water",
  "The Tree of Life",
  "TRON",
  "What Dreams May Come",
  "Who Framed Roger Rabbit",
];

export const video = [
  "► CUSTOM (enter below)",
  "███████████ MY DATA ███████████",
  "Doom",
  "██████ PROMPTER CLOUD DATA ██████",
  "▬▬▬▬▬ Popular Games",
  "Animal Crossing New Horizons",
  "BioShock",
  "Borderlands 2",
  "Call of Duty",
  "Diablo III",
  "Doom",
  "Duck Hunt",
  "Elden Ring",
  "Fallout",
  "FIFA 18",
  "GoldenEye 007",
  "Gran Turismo",
  "Grand Theft Auto",
  "Half Life",
  "Halo",
  "Human Fall Flat",
  "Kinect Adventures",
  "LittleBigPlanet",
  "Mario Kart",
  "Metal Gear Solid",
  "Metroid Prime",
  "Minecraft",
  "Nintendogs",
  "Pac-Man",
  "Perfect Dark",
  "Pokémon",
  "Portal",
  "PUBG Battlegrounds",
  "Quake",
  "Red Dead Redemption",
  "Resident Evil",
  "Skyrim",
  "Sonic the Hedgehog",
  "Super Mario 64",
  "Tekken 3",
  "Terraria",
  "Tetris",
  "The Elder Scrolls V Skyrim",
  "The Legend of Zelda Majora's Mask",
  "The Legend of Zelda Ocarina of Time",
  "The Witcher 3",
  "Tony Hawk's Pro Skater",
  "Wii Fit",
  "Wii Play",
  "Wii Sports",
  "World of Goo",
  "Worms World Party",
];
